/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package readadventure;
import java.awt.Cursor;
import java.awt.Color; // Se agrega la importación para manejar colores
import java.awt.event.ActionEvent; // Se agrega la importación para manejar eventos de acción
import javax.swing.BorderFactory; // Se agrega la importación para usar BorderFactory
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    public Login() {
        initComponents();
        BTNBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
        BTNIngreso.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reg_init = new javax.swing.JPanel();
        BTNBack = new readadventure.Boton();
        LBLPass = new javax.swing.JLabel();
        TxTPass = new javax.swing.JTextField();
        TxTName = new javax.swing.JTextField();
        LBLName = new javax.swing.JLabel();
        BTNIngreso = new readadventure.Boton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(310, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reg_init.setBackground(new java.awt.Color(95, 43, 93));
        Reg_init.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNBack.setForeground(new java.awt.Color(255, 255, 255));
        BTNBack.setText("<-");
        BTNBack.setBorderColor(new java.awt.Color(0, 0, 0));
        BTNBack.setBorderPainted(false);
        BTNBack.setColor(new java.awt.Color(255, 213, 82));
        BTNBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNBackMouseClicked(evt);
            }
        });
        BTNBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBackActionPerformed(evt);
            }
        });
        Reg_init.add(BTNBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 53, -1));

        LBLPass.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        LBLPass.setForeground(new java.awt.Color(255, 255, 255));
        LBLPass.setText("Contraseña");
        Reg_init.add(LBLPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        TxTPass.setText("jTextField1");
        Reg_init.add(TxTPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 80, -1));

        TxTName.setText("jTextField1");
        TxTName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxTNameActionPerformed(evt);
            }
        });
        Reg_init.add(TxTName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        LBLName.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        LBLName.setForeground(new java.awt.Color(255, 255, 255));
        LBLName.setText("Cédula");
        Reg_init.add(LBLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        BTNIngreso.setForeground(new java.awt.Color(255, 255, 255));
        BTNIngreso.setText("Ingresar");
        BTNIngreso.setBorderColor(new java.awt.Color(0, 0, 0));
        BTNIngreso.setColor(new java.awt.Color(204, 0, 0));
        BTNIngreso.setColorClick(new java.awt.Color(204, 0, 153));
        BTNIngreso.setColorOver(new java.awt.Color(204, 204, 0));
        BTNIngreso.setRadius(10);
        Reg_init.add(BTNIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        add(Reg_init, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void BTNBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNBackMouseClicked
        Main mainFrame = (Main) javax.swing.SwingUtilities.getWindowAncestor(this);
        mainFrame.showInicioPanel();
        Reg_init.setVisible(false);
        
    }//GEN-LAST:event_BTNBackMouseClicked

    private void BTNBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNBackActionPerformed

    private void TxTNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxTNameActionPerformed
        
    }//GEN-LAST:event_TxTNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private readadventure.Boton BTNBack;
    private readadventure.Boton BTNIngreso;
    private javax.swing.JLabel LBLName;
    private javax.swing.JLabel LBLPass;
    private javax.swing.JPanel Reg_init;
    private javax.swing.JTextField TxTName;
    private javax.swing.JTextField TxTPass;
    // End of variables declaration//GEN-END:variables
}
