/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package readadventure;
import java.awt.Cursor;

/**
 *
 * @author PC
 */
public class Main extends javax.swing.JFrame {
    
    /**
     * Creates new form Main
     */
    
    
    
    public Main() {
        initComponents();
        
        
        BTNHelp.setCursor(new Cursor(Cursor.HAND_CURSOR));
        BtnLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        BtnRegister.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Animacion = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        BtnLogin = new readadventure.Boton();
        BtnRegister = new readadventure.Boton();
        BTNHelp = new readadventure.Boton();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Animacion.setBackground(new java.awt.Color(255, 255, 255));
        Animacion.setPreferredSize(new java.awt.Dimension(310, 500));

        Inicio.setBackground(new java.awt.Color(95, 43, 93));
        Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnLogin.setBackground(new java.awt.Color(0, 196, 166));
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Iniciar Sesion");
        BtnLogin.setColor(new java.awt.Color(0, 196, 166));
        BtnLogin.setRadius(25);
        BtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLoginMouseClicked(evt);
            }
        });
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        Inicio.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 58));

        BtnRegister.setBackground(new java.awt.Color(254, 43, 138));
        BtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegister.setText("Crear Cuenta");
        BtnRegister.setColor(new java.awt.Color(254, 43, 138));
        BtnRegister.setRadius(25);
        BtnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegisterMouseClicked(evt);
            }
        });
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });
        Inicio.add(BtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 157, 58));

        BTNHelp.setBorder(null);
        BTNHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bloque2.png"))); // NOI18N
        BTNHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHelpActionPerformed(evt);
            }
        });
        Inicio.add(BTNHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 30, 30));

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Necesitas Ayuda?");
        Inicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        javax.swing.GroupLayout AnimacionLayout = new javax.swing.GroupLayout(Animacion);
        Animacion.setLayout(AnimacionLayout);
        AnimacionLayout.setHorizontalGroup(
            AnimacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnimacionLayout.createSequentialGroup()
                .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AnimacionLayout.setVerticalGroup(
            AnimacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnimacionLayout.createSequentialGroup()
                .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Animacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 310, -1));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/wallpaperflare.com_wallpaper.jpg"))); // NOI18N
        Background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Background.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void BtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseClicked
        // TODO add your handling code here:
        Animacion.setLocation(490, 0);
        Animacion.setSize(310,500);
        Animacion.revalidate();
        Animacion.repaint();
        
        Login Log_dim = new Login();
        Log_dim.setSize(310, 500);
        Log_dim.setLocation(0,0);
        Animacion.removeAll();
        Animacion.add(Log_dim);
        Animacion.revalidate();
        Animacion.repaint();
        
        
    }//GEN-LAST:event_BtnLoginMouseClicked

    private void BtnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegisterMouseClicked
        Animacion.setLocation(490, 0);
        Animacion.setSize(310,500);
        Animacion.revalidate();
        Animacion.repaint();

        
        
        Register Reg_dim = new Register();
        Reg_dim.setSize(310, 500);
        Reg_dim.setLocation(0,0);
        Animacion.removeAll();
        Animacion.add(Reg_dim);
        Animacion.revalidate();
        Animacion.repaint();
    }//GEN-LAST:event_BtnRegisterMouseClicked

    private void BTNHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHelpActionPerformed
        Animacion.setLocation(490, 0);
        Animacion.setSize(310,500);
        Animacion.revalidate();
        Animacion.repaint();

        
        
        Help Reg_dim = new Help ();
        Reg_dim.setSize(310, 500);
        Reg_dim.setLocation(0,0);
        Animacion.removeAll();
        Animacion.add(Reg_dim);
        Animacion.revalidate();
        Animacion.repaint();
    }//GEN-LAST:event_BTNHelpActionPerformed

    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void showInicioPanel() {
        Animacion.removeAll();
        Animacion.add(Inicio);
        Animacion.revalidate();
        Animacion.repaint();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Animacion;
    private readadventure.Boton BTNHelp;
    private readadventure.Boton BtnLogin;
    private readadventure.Boton BtnRegister;
    private javax.swing.JPanel Inicio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
