/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package readadventure;
import java.awt.Cursor;

/**
 *
 * @author PC
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        BTNBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
        BTNIngreso.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reg_init = new javax.swing.JPanel();
        BTNBack = new readadventure.Boton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        TxTNombre = new javax.swing.JTextField();
        BTNIngreso = new readadventure.Boton();

        setBackground(new java.awt.Color(95, 43, 93));
        setMaximumSize(new java.awt.Dimension(300, 500));
        setPreferredSize(new java.awt.Dimension(310, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reg_init.setBackground(new java.awt.Color(95, 43, 93));
        Reg_init.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNBack.setBackground(new java.awt.Color(245, 196, 45));
        BTNBack.setForeground(new java.awt.Color(255, 255, 255));
        BTNBack.setText("<-");
        BTNBack.setBorderColor(new java.awt.Color(51, 51, 0));
        BTNBack.setColor(new java.awt.Color(255, 255, 0));
        BTNBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNBackMouseClicked(evt);
            }
        });
        Reg_init.add(BTNBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 53, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña");
        Reg_init.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cedula");
        Reg_init.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        Reg_init.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jTextField1.setText("jTextField1");
        Reg_init.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 130, -1));

        jTextField2.setText("jTextField2");
        Reg_init.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 130, -1));

        TxTNombre.setText("jTextField2");
        Reg_init.add(TxTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 130, -1));

        BTNIngreso.setForeground(new java.awt.Color(255, 255, 255));
        BTNIngreso.setText("Registrarse");
        BTNIngreso.setBorderColor(new java.awt.Color(0, 0, 0));
        BTNIngreso.setColor(new java.awt.Color(204, 0, 0));
        BTNIngreso.setRadius(10);
        Reg_init.add(BTNIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        add(Reg_init, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void BTNBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNBackMouseClicked
        Main mainFrame = (Main) javax.swing.SwingUtilities.getWindowAncestor(this);
        mainFrame.showInicioPanel();
        Reg_init.setVisible(false);
        
    }//GEN-LAST:event_BTNBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private readadventure.Boton BTNBack;
    private readadventure.Boton BTNIngreso;
    private javax.swing.JPanel Reg_init;
    private javax.swing.JTextField TxTNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
