
package ReAdventure.Swing.panels;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;

/**
 *
 * @author PC
 */
public class PanelForgetPassword extends javax.swing.JPanel {


    public PanelForgetPassword() {
        initComponents();
        setOpaque(false);
        setFocusCycleRoot(true);
        super.setVisible(false);

        addMouseListener(new MouseAdapter(){  
        });
    }

    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        Cedula.addKeyListener(new KeyListener() {
        @Override
            public void keyTyped(KeyEvent e) {
             CedulaKeyTyped(e);
            }
        @Override
            public void keyPressed(KeyEvent e) {
            // Método requerido por la interfaz KeyListener
            }
        @Override
           public void keyReleased(KeyEvent e) {
        // Método requerido por la interfaz KeyListener
        }
        });
        if(aFlag){
            Cedula.grabFocus();
            Cedula.setText("");
        }
    }
    
    private void CedulaKeyTyped(java.awt.event.KeyEvent evt){
       char key = evt.getKeyChar();
        if (!(Character.isDigit(key) || key == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); // Consume el evento para evitar que el carácter sea ingresado
        } else if (Cedula.getText().length() >= 10) {
            evt.consume(); // Limita la longitud del texto a 10 caracteres
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new ReAdventure.Swing.controls.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cedula = new ReAdventure.Swing.controls.MyTextField();
        Cancelar_0 = new ReAdventure.Swing.controls.ButtonOutLine();
        Verificar_0 = new ReAdventure.Swing.controls.ButtonOutLine();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelRound1.setPreferredSize(new java.awt.Dimension(450, 600));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 63, 63));
        jLabel1.setText("Olvidaste tu contraseña");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(63, 63, 63));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingresa tu cédula");

        Cancelar_0.setBackground(new java.awt.Color(255, 0, 0));
        Cancelar_0.setForeground(new java.awt.Color(0, 0, 0));
        Cancelar_0.setText("Cancelar");
        Cancelar_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_0ActionPerformed(evt);
            }
        });

        Verificar_0.setBackground(new java.awt.Color(72, 213, 51));
        Verificar_0.setForeground(new java.awt.Color(0, 0, 0));
        Verificar_0.setText("Verificar");
        Verificar_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Verificar_0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(Verificar_0, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Cancelar_0, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Verificar_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed

    }//GEN-LAST:event_CedulaActionPerformed

    private void Cancelar_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_0ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_Cancelar_0ActionPerformed

    private void Verificar_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Verificar_0ActionPerformed
        // funcion de validar la cedula
        // funcion para comprobar la cedula en la base de datos
        
    }//GEN-LAST:event_Verificar_0ActionPerformed

    private void VerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonOutLine2ActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setColor(new Color(50,50,50));
        g2.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f));
        g2.fillRect(0, 0, getWidth(), getHeight());
        g2.setComposite(AlphaComposite.SrcOver);
        super.paintComponent(g);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ReAdventure.Swing.controls.ButtonOutLine Cancelar_0;
    private ReAdventure.Swing.controls.MyTextField Cedula;
    private ReAdventure.Swing.controls.ButtonOutLine Verificar_0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private ReAdventure.Swing.controls.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
